CREATE TABLE USER
(
  ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID   VARCHAR(100),
  NAME         VARCHAR(100),
  TOKEN        VARCHAR(36),
  GMT_CREATE   BIGINT,
  GMT_MODIFIED BIGINT,
  BIO          VARCHAR(256),
  AVATAR_URL   VARCHAR(100)
);